# Generated by Django 5.2.7 on 2025-12-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tables', '0002_documentcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'ordering': ['-default_selection', 'name'], 'verbose_name': 'Categoria de Documento', 'verbose_name_plural': 'Categorias de Documentos'},
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='default_selection',
            field=models.BooleanField(default=False, help_text='Se selecionado, esta categoria de documento será exibida primeiro na lista de categorias de documentos', verbose_name='Seleção Padrão'),
        ),
        migrations.AlterUniqueTogether(
            name='documentcategory',
            unique_together={('name', 'acronym')},
        ),
    ]
