# Generated by Django 5.2.8 on 2025-11-29 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_tables', '0001_initial'),
        ('core', '0001_initial'),
        ('requisitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Excluído em')),
                ('version', models.IntegerField(default=1, verbose_name='Versão do Registro')),
                ('requested_at', models.DateTimeField(blank=True, help_text='Data e hora da solicitação', null=True, verbose_name='Solicitada em')),
                ('requested_device_amount', models.PositiveSmallIntegerField(blank=True, default=1, help_text='Quantidade de dispositivos solicitados', null=True, verbose_name='Quantidade de Dispositivos')),
                ('requester_reply_email', models.EmailField(blank=True, help_text='E-mail de resposta', max_length=254, null=True, verbose_name='E-mail de Resposta')),
                ('requester_authority_name', models.CharField(blank=True, help_text='Nome completo da autoridade solicitante', max_length=300, null=True, verbose_name='Nome da Autoridade')),
                ('request_procedures', models.CharField(blank=True, help_text='Procedimentos (ex: IP, PJ, etc)', max_length=512, null=True, verbose_name='Procedimentos')),
                ('additional_info', models.TextField(blank=True, help_text='Informações adicionais', null=True, verbose_name='Informações Adicionais')),
                ('number', models.CharField(blank=True, help_text='Número do processo.', max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, editable=False, help_text='Ano do processo para controle de numeração sequencial (controlado pelo sistema).', null=True)),
                ('status', models.CharField(choices=[('draft', 'Cadastrto Incompleto'), ('waiting_extractor', 'Aguardando Extrator'), ('waiting_start', 'Aguardando início'), ('in_progress', 'Em progresso'), ('paused', 'Pausado'), ('completed', 'Concluído'), ('waiting_collect', 'Aguardando coleta')], default='draft', help_text='Status do processo.', max_length=50)),
                ('priority', models.IntegerField(choices=[(0, 'Baixa'), (1, 'Média'), (2, 'Alta'), (3, 'Urgente')], default=0, help_text='Prioridade do processo.')),
                ('assigned_at', models.DateTimeField(blank=True, help_text='Data em que o processo foi atribuída.', null=True)),
                ('registration_completed_at', models.DateTimeField(blank=True, help_text='Data em que o cadastro do processo foi completado.', null=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='Data em que o processo foi finalizado.', null=True)),
                ('finalization_notes', models.TextField(blank=True, help_text='Observações sobre a finalização do processo.', null=True)),
                ('dispatch_number', models.CharField(blank=True, help_text='Número do ofício de resposta do processo.', max_length=50, null=True)),
                ('dispatch_date', models.DateField(blank=True, help_text='Data do ofício de resposta do processo.', null=True)),
                ('dispatch_file', models.BinaryField(blank=True, help_text='Arquivo do ofício de resposta do processo.', null=True)),
                ('dispatch_filename', models.CharField(blank=True, help_text='Nome original do arquivo do ofício de resposta do processo.', max_length=255, null=True)),
                ('dispatch_content_type', models.CharField(blank=True, help_text='Tipo de conteúdo do arquivo do ofício de resposta do processo (MIME type).', max_length=100, null=True)),
                ('is_legacy', models.BooleanField(default=False, help_text='Campo para identificar extrações legadas.')),
                ('legacy_number', models.CharField(blank=True, help_text='Número legado do processo.', max_length=50, null=True)),
                ('legacy_notes', models.TextField(blank=True, help_text='Observações legadas do processo.', null=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='atribuído por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_extraction_cases', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Usuário responsável pelo processo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_extraction_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('crime_category', models.ForeignKey(blank=True, help_text='Categoria de Crime', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_crime_types', to='base_tables.crimecategory', verbose_name='Categoria de Crime')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('extraction_request', models.OneToOneField(blank=True, help_text='Solicitação de extração.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case', to='requisitions.extractionrequest')),
                ('extraction_unit', models.ForeignKey(blank=True, help_text='Unidade de extração', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_requested_extraction_units', to='core.extractionunit', verbose_name='Unidade de Extração')),
                ('finished_by', models.ForeignKey(blank=True, help_text='finalizado por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_by_extraction_cases', to=settings.AUTH_USER_MODEL)),
                ('requester_agency_unit', models.ForeignKey(blank=True, help_text='Unidade solicitante', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_requester_agency_units', to='base_tables.agencyunit', verbose_name='Unidade Solicitante')),
                ('requester_authority_position', models.ForeignKey(blank=True, help_text='Cargo da autoridade solicitante', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_requester_authority_positions', to='base_tables.employeeposition', verbose_name='Cargo da Autoridade')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'db_table': 'case',
            },
        ),
        migrations.CreateModel(
            name='CaseProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Excluído em')),
                ('version', models.IntegerField(default=1, verbose_name='Versão do Registro')),
                ('number', models.CharField(blank=True, help_text='Número do procedimento.', max_length=50, null=True)),
                ('document_file', models.BinaryField(blank=True, help_text='Arquivo do documento.', null=True)),
                ('original_filename', models.CharField(blank=True, help_text='Nome original do arquivo.', max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, help_text='Tipo de conteúdo do arquivo (MIME type).', max_length=100, null=True)),
                ('case', models.ForeignKey(help_text='Processo.', on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('procedure_category', models.ForeignKey(blank=True, help_text='Categoria do procedimento.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_procedures', to='base_tables.procedurecategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Procedimento do Processo',
                'verbose_name_plural': 'Procedimentos do Processo',
                'db_table': 'case_procedure',
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['number'], name='case_number_349400_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='case_status_deb121_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['priority'], name='case_priorit_bccbdf_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['extraction_unit'], name='case_extract_160696_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['year'], name='case_year_55f438_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['assigned_to'], name='case_assigne_830f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['created_at'], name='case_created_11695f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('extraction_unit', 'year', 'number')},
        ),
        migrations.AddIndex(
            model_name='caseprocedure',
            index=models.Index(fields=['case'], name='case_proced_case_id_b152ff_idx'),
        ),
        migrations.AddIndex(
            model_name='caseprocedure',
            index=models.Index(fields=['created_at'], name='case_proced_created_24c4da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caseprocedure',
            unique_together={('case', 'number', 'procedure_category')},
        ),
    ]
