# Generated by Django 5.2.8 on 2025-11-30 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tables', '0001_initial'),
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Excluído em')),
                ('version', models.IntegerField(default=1, verbose_name='Versão do Registro')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cor')),
                ('is_imei_unknown', models.BooleanField(blank=True, null=True, verbose_name='IMEI Desconhecido')),
                ('imei_01', models.CharField(blank=True, max_length=50, null=True, verbose_name='IMEI 01')),
                ('imei_02', models.CharField(blank=True, max_length=50, null=True, verbose_name='IMEI 02')),
                ('imei_03', models.CharField(blank=True, max_length=50, null=True, verbose_name='IMEI 03')),
                ('imei_04', models.CharField(blank=True, max_length=50, null=True, verbose_name='IMEI 04')),
                ('imei_05', models.CharField(blank=True, max_length=50, null=True, verbose_name='IMEI 05')),
                ('owner_name', models.CharField(help_text='Nome do Proprietário', max_length=200, null=True, verbose_name='Nome do Proprietário')),
                ('internal_storage', models.PositiveIntegerField(blank=True, help_text='Capacidade de armazenamento interna do dispositivo em GB (ex: iPhone 512GB)', null=True, verbose_name='Armazenamento Interno (GB)')),
                ('is_turned_on', models.BooleanField(blank=True, null=True, verbose_name='Ligado')),
                ('is_locked', models.BooleanField(blank=True, null=True, verbose_name='Bloqueado')),
                ('is_password_known', models.BooleanField(blank=True, null=True, verbose_name='Senha Conhecida')),
                ('password_type', models.CharField(blank=True, choices=[('pin', 'PIN'), ('password', 'Senha'), ('pattern', 'Padrão'), ('bio', 'Biometria'), ('none', 'Nenhum')], help_text='Tipo', max_length=20, null=True, verbose_name='Tipo de Senha')),
                ('password', models.CharField(blank=True, help_text='Senha', max_length=100, null=True, verbose_name='Senha')),
                ('is_damaged', models.BooleanField(blank=True, null=True, verbose_name='Danificado')),
                ('damage_description', models.CharField(blank=True, help_text='Descrição dos danos', max_length=200, null=True, verbose_name='Descrição dos danos')),
                ('has_fluids', models.BooleanField(blank=True, help_text='Indica se há presença de fluidos no dispositivo', null=True, verbose_name='Presença de Fluidos')),
                ('fluids_description', models.CharField(blank=True, help_text='Descreva os fluidos. Ex.: sangue, água, óleo, etc.', max_length=200, null=True, verbose_name='Descrição dos flúidos')),
                ('has_sim_card', models.BooleanField(blank=True, help_text='Indica se há presença de chip SIM no dispositivo', null=True, verbose_name='Chip SIM')),
                ('sim_card_info', models.CharField(blank=True, help_text='Informações sobre o chip, se houver', max_length=200, null=True, verbose_name='Informações do Chip')),
                ('has_memory_card', models.BooleanField(blank=True, help_text='Indica se há presença de cartão de memória no dispositivo', null=True, verbose_name='Cartão de Memória')),
                ('memory_card_info', models.CharField(blank=True, help_text='Informações sobre o cartão de memória, se houver', max_length=200, null=True, verbose_name='Informações do Cartão de Memória')),
                ('has_other_accessories', models.BooleanField(blank=True, help_text='Indica se há presença de outros acessórios no dispositivo', null=True, verbose_name='Outros Acessórios')),
                ('other_accessories_info', models.CharField(blank=True, help_text='Ex.: Capa, Carregador, etc.', max_length=200, null=True, verbose_name='Informações dos Outros Acessórios')),
                ('is_sealed', models.BooleanField(blank=True, null=True, verbose_name='Lacrado')),
                ('security_seal', models.CharField(blank=True, help_text='Número do lacre', max_length=100, null=True, verbose_name='Número do Lacre')),
                ('additional_info', models.TextField(blank=True, help_text='Informações adicionais sobre o dispositivo', null=True, verbose_name='Informações Adicionais')),
                ('case', models.ForeignKey(help_text='Processo relacionado a este dispositivo', on_delete=django.db.models.deletion.PROTECT, related_name='case_devices', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('device_category', models.ForeignKey(help_text='Categoria do dispositivo', on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='base_tables.devicecategory', verbose_name='Categoria')),
                ('device_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='base_tables.devicemodel', verbose_name='Modelo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Dispositivo do Processo',
                'verbose_name_plural': 'Dispositivos do Processo',
                'db_table': 'case_device',
                'indexes': [models.Index(fields=['case'], name='case_device_case_id_efca76_idx'), models.Index(fields=['device_model'], name='case_device_device__5cca85_idx'), models.Index(fields=['created_at'], name='case_device_created_a07330_idx')],
                'unique_together': {('case', 'device_model', 'color')},
            },
        ),
    ]
