# Generated by Django 5.2.8 on 2025-12-02 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_casedevice'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Excluído em')),
                ('version', models.IntegerField(default=1, verbose_name='Versão do Registro')),
                ('status', models.CharField(choices=[('pending', 'Aguardando Extrator'), ('assigned', 'Aguardando Início'), ('in_progress', 'Em Andamento'), ('paused', 'Pausado'), ('completed', 'Finalizada')], default='pending', help_text='Status da extração.', max_length=50)),
                ('assigned_at', models.DateTimeField(blank=True, help_text='Data de atribuição.', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='Data de início da extração.', null=True)),
                ('started_notes', models.TextField(blank=True, help_text='Observações sobre o início da extração.', null=True, verbose_name='Observações do Início da Extração')),
                ('finished_at', models.DateTimeField(blank=True, help_text='Data de término da extração.', null=True)),
                ('finished_notes', models.TextField(blank=True, help_text='Observações sobre o término da extração.', null=True, verbose_name='Observações do Término da Extração')),
                ('extraction_result', models.CharField(blank=True, choices=[('success', 'Bem-Sucedida'), ('failed', 'Falhou'), ('partial', 'Parcial')], help_text='Resultado da extração do dispositivo.', max_length=50, null=True, verbose_name='Resultado da Extração')),
                ('extraction_results_notes', models.TextField(blank=True, help_text='Observações sobre o resultado da extração.', null=True, verbose_name='Observações do Resultado da Extração')),
                ('brute_force_started_at', models.DateTimeField(blank=True, help_text='Data de início da força bruta.', null=True)),
                ('brute_force_started_notes', models.TextField(blank=True, help_text='Observações sobre o início da força bruta.', null=True, verbose_name='Observações do Início da Força Bruta')),
                ('brute_force_finished_at', models.DateTimeField(blank=True, help_text='Data de término da força bruta.', null=True)),
                ('brute_force_result', models.BooleanField(default=False, help_text='Força Bruta bem-sucedida.', verbose_name='Força Bruta Bem-Sucedida')),
                ('brute_force_results_notes', models.TextField(blank=True, help_text='Observações da força bruta.', null=True, verbose_name='Observações da força bruta')),
                ('cellebrite_premium', models.BooleanField(default=False, help_text='Indica se o dispositivo é um Cellebrite Premium', verbose_name='Cellebrite Premium')),
                ('cellebrite_premium_notes', models.TextField(blank=True, help_text='Observações sobre o Cellebrite Premium do dispositivo', null=True, verbose_name='Observações do Cellebrite Premium')),
                ('cellebrite_premium_support', models.BooleanField(default=False, help_text='Indica se o dispositivo tem suporte a Cellebrite Premium', verbose_name='Suporte Cellebrite Premium')),
                ('cellebrite_premium_support_notes', models.TextField(blank=True, help_text='Observações sobre o suporte a Cellebrite Premium do dispositivo', null=True, verbose_name='Observações do Suporte Cellebrite Premium')),
                ('logical_extraction', models.BooleanField(default=False, help_text='Indica se o dispositivo é uma extração lógica', verbose_name='Extração Lógica')),
                ('logical_extraction_notes', models.TextField(blank=True, help_text='Observações sobre a extração lógica do dispositivo', null=True, verbose_name='Observações da Extração Lógica')),
                ('physical_extraction', models.BooleanField(default=False, help_text='Indica se o dispositivo é uma extração física', verbose_name='Extração Física')),
                ('physical_extraction_notes', models.TextField(blank=True, help_text='Observações sobre a extração física do dispositivo', null=True, verbose_name='Observações da Extração Física')),
                ('full_file_system_extraction', models.BooleanField(default=False, help_text='Indica se o dispositivo é uma extração completa do sistema de arquivos', verbose_name='Extração Completa do Sistema de Arquivos')),
                ('full_file_system_extraction_notes', models.TextField(blank=True, help_text='Observações sobre a extração completa do sistema de arquivos do dispositivo', null=True, verbose_name='Observações da Extração Completa do Sistema de Arquivos')),
                ('cloud_extraction', models.BooleanField(default=False, help_text='Indica se o dispositivo é uma extração em nuvem', verbose_name='Extração em Nuvem')),
                ('cloud_extraction_notes', models.TextField(blank=True, help_text='Observações sobre a extração em nuvem do dispositivo', null=True, verbose_name='Observações da Extração em Nuvem')),
                ('extraction_size', models.PositiveIntegerField(default=0, help_text='Tamanho da extração em GB', null=True, verbose_name='Tamanho da Extração (GB)')),
                ('assigned_by', models.ForeignKey(help_text='Usuário responsável pela extração.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by_extractions', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(help_text='Usuário responsável pela extração.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_extractions', to='core.extractoruser')),
                ('brute_force_finished_by', models.ForeignKey(help_text='Usuário que finalizou a força bruta.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brute_force_finished_extractions', to=settings.AUTH_USER_MODEL)),
                ('brute_force_started_by', models.ForeignKey(help_text='Usuário que iniciou a força bruta.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brute_force_started_extractions', to=settings.AUTH_USER_MODEL)),
                ('case_device', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='device_extraction', to='cases.casedevice', verbose_name='Dispositivo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('finished_by', models.ForeignKey(help_text='Usuário que finalizou a extração.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finished_extractions', to='core.extractoruser')),
                ('started_by', models.ForeignKey(help_text='Usuário que iniciou a extração.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='started_extractions', to='core.extractoruser')),
                ('storage_media', models.ForeignKey(blank=True, help_text='Local de armazenamento onde a extração está salva', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extractions', to='core.extractionunitstoragemedia')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Extração',
                'verbose_name_plural': 'Extrações',
                'db_table': 'extraction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='extraction_status_3daedd_idx'), models.Index(fields=['assigned_to'], name='extraction_assigne_bb18c6_idx'), models.Index(fields=['started_at'], name='extraction_started_87137b_idx'), models.Index(fields=['finished_at'], name='extraction_finishe_73d665_idx'), models.Index(fields=['extraction_result'], name='extraction_extract_acf7a2_idx'), models.Index(fields=['case_device', 'status'], name='extraction_case_de_2c1e56_idx')],
            },
        ),
    ]
