# Generated by Django 4.2.26 on 2025-12-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_extraction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='casedevice',
            unique_together=set(),
        ),
    ]
