# Generated by Django 4.2.26 on 2025-12-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_remove_casedevice_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='paused_notes',
            field=models.TextField(blank=True, help_text='Observações sobre a pausa da extração.', null=True, verbose_name='Observações da Pausa da Extração'),
        ),
        migrations.AlterField(
            model_name='casedevice',
            name='password_type',
            field=models.CharField(blank=True, choices=[('pin', 'PIN'), ('numeric', 'Numérica'), ('alphanumeric', 'Alfanumérica'), ('pattern', 'Desenho de Padrão'), ('biometric', 'Biométrica'), ('none', 'Nenhuma Senha'), ('other', 'Outras')], help_text='Tipo', max_length=20, null=True, verbose_name='Tipo de Senha'),
        ),
    ]
