# Generated by Django 5.2.8 on 2025-12-16 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tables', '0002_documentcategory'),
        ('cases', '0005_add_paused_notes_to_extraction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Excluído em')),
                ('version', models.IntegerField(default=1, verbose_name='Versão do Registro')),
                ('number', models.CharField(blank=True, help_text='Número do documento.', max_length=50, null=True)),
                ('document_file', models.BinaryField(blank=True, help_text='Arquivo do documento.', null=True)),
                ('original_filename', models.CharField(blank=True, help_text='Nome original do arquivo.', max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, help_text='Tipo de conteúdo do arquivo (MIME type).', max_length=100, null=True)),
                ('case', models.ForeignKey(help_text='Processo.', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('document_category', models.ForeignKey(blank=True, help_text='Categoria do documento.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_documents', to='base_tables.documentcategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Documento do Processo',
                'verbose_name_plural': 'Documentos do Processo',
                'db_table': 'case_document',
                'indexes': [models.Index(fields=['case'], name='case_docume_case_id_538985_idx'), models.Index(fields=['created_at'], name='case_docume_created_57f97a_idx')],
                'unique_together': {('case', 'number', 'document_category')},
            },
        ),
    ]
