# Generated by Django 5.2.8 on 2025-12-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_casedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Cadastrto Incompleto'),
                    ('waiting_extractor', 'Aguardando Extrator'),
                    ('waiting_start', 'Aguardando início'),
                    ('in_progress', 'Em progresso'),
                    ('paused', 'Pausado'),
                    ('extractions_completed', 'Extrações concluídas'),
                    ('completed', 'Concluído'),
                    ('waiting_collect', 'Aguardando coleta'),
                ],
                default='draft',
                help_text='Status do processo.',
                max_length=50,
            ),
        ),
    ]
