# Generated by Django 5.2.8 on 2025-12-16 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchSequenceNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Excluído em')),
                ('version', models.IntegerField(default=1, verbose_name='Versão do Registro')),
                ('year', models.IntegerField(help_text='Ano para controle da numeração sequencial', verbose_name='Ano')),
                ('last_number', models.IntegerField(default=0, help_text='Último número de ofício gerado para esta unidade e ano', verbose_name='Último Número')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('extraction_unit', models.ForeignKey(help_text='Unidade de extração', on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_sequence_numbers', to='core.extractionunit', verbose_name='Unidade de Extração')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Numeração Sequencial de Ofício',
                'verbose_name_plural': 'Numerações Sequenciais de Ofícios',
                'db_table': 'dispatch_sequence_number',
                'ordering': ['-year', '-last_number'],
                'indexes': [models.Index(fields=['extraction_unit', 'year'], name='dispatch_se_extract_0bf800_idx')],
                'unique_together': {('extraction_unit', 'year')},
            },
        ),
        migrations.CreateModel(
            name='DispatchTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Excluído em')),
                ('version', models.IntegerField(default=1, verbose_name='Versão do Registro')),
                ('name', models.CharField(help_text='Nome identificador do template', max_length=255, verbose_name='Nome do Template')),
                ('description', models.TextField(blank=True, help_text='Descrição do template', null=True, verbose_name='Descrição')),
                ('template_file', models.BinaryField(blank=True, help_text='Arquivo ODT do template', null=True, verbose_name='Arquivo Template')),
                ('template_filename', models.CharField(blank=True, help_text='Nome original do arquivo template', max_length=255, null=True, verbose_name='Nome do Arquivo')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o template está ativo e pode ser usado', verbose_name='Ativo')),
                ('is_default', models.BooleanField(default=False, help_text='Indica se este é o template padrão para a unidade', verbose_name='Padrão')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('extraction_unit', models.ForeignKey(help_text='Unidade de extração', on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_templates', to='core.extractionunit', verbose_name='Unidade de Extração')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Template de Ofício',
                'verbose_name_plural': 'Templates de Ofícios',
                'db_table': 'dispatch_template',
                'ordering': ['-is_default', '-is_active', 'name'],
                'indexes': [models.Index(fields=['extraction_unit', 'is_active'], name='dispatch_te_extract_cec7a1_idx'), models.Index(fields=['extraction_unit', 'is_default'], name='dispatch_te_extract_a9954c_idx')],
            },
        ),
    ]
