# Generated by Django 5.2.8 on 2025-12-16 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dispatchsequencenumber_dispatchtemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Excluído em')),
                ('version', models.IntegerField(default=1, verbose_name='Versão do Registro')),
                ('name', models.CharField(help_text='Nome identificador do template', max_length=255, verbose_name='Nome do Template')),
                ('description', models.TextField(blank=True, help_text='Descrição do template', null=True, verbose_name='Descrição')),
                ('header_left_logo', models.BinaryField(blank=True, help_text='Logo do cabeçalho esquerdo do template', null=True, verbose_name='Logo do Cabeçalho Esquerdo')),
                ('header_right_logo', models.BinaryField(blank=True, help_text='Logo do cabeçalho direito do template', null=True, verbose_name='Logo do Cabeçalho Direito')),
                ('header_text', models.TextField(blank=True, help_text='Texto do cabeçalho do template', null=True, verbose_name='Texto do Cabeçalho')),
                ('subject_text', models.TextField(blank=True, help_text='Texto do assunto do template', null=True, verbose_name='Texto do Assunto')),
                ('body_text', models.TextField(blank=True, help_text='Texto do corpo do template', null=True, verbose_name='Texto do Corpo do Template')),
                ('signature_text', models.TextField(blank=True, help_text='Texto da assinatura do template', null=True, verbose_name='Texto da Assinatura')),
                ('watermark_text', models.TextField(blank=True, help_text='Texto da água-marinha do template', null=True, verbose_name='Texto da Água-Marinha')),
                ('watermark_logo', models.BinaryField(blank=True, help_text='Logo da água-marinha do template', null=True, verbose_name='Logo da Água-Marinha')),
                ('footer_left_logo', models.BinaryField(blank=True, help_text='Logo do rodapé esquerdo do template', null=True, verbose_name='Logo do Rodapé Esquerdo')),
                ('footer_right_logo', models.BinaryField(blank=True, help_text='Logo do rodapé direito do template', null=True, verbose_name='Logo do Rodapé Direito')),
                ('footer_text', models.TextField(blank=True, help_text='Texto do rodapé do template', null=True, verbose_name='Texto do Rodapé')),
                ('is_default', models.BooleanField(default=False, help_text='Indica se este é o template padrão para a unidade', verbose_name='Padrão')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('extraction_unit', models.ForeignKey(help_text='Unidade de extração', on_delete=django.db.models.deletion.PROTECT, related_name='document_templates', to='core.extractionunit', verbose_name='Unidade de Extração')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Template de Documento',
                'verbose_name_plural': 'Templates de Documentos',
                'db_table': 'document_template',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='DispatchTemplate',
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['extraction_unit', 'is_default'], name='document_te_extract_9ad90a_idx'),
        ),
    ]
