# Generated by Django 4.2.26 on 2025-12-17 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_documenttemplate_delete_dispatchtemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionUnitReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Excluído em')),
                ('version', models.IntegerField(default=1, verbose_name='Versão do Registro')),
                ('reports_enabled', models.BooleanField(default=True, help_text='Ativar relatórios para esta unidade', verbose_name='Relatórios Ativados')),
                ('default_report_header_logo', models.BinaryField(blank=True, help_text='Logo do relatório (formato binário)', null=True, verbose_name='Logo do Relatório')),
                ('secondary_report_header_logo', models.BinaryField(blank=True, help_text='Logo secundária do relatório (formato binário)', null=True, verbose_name='Logo Secundária do Relatório')),
                ('distribution_report_notes', models.TextField(blank=True, help_text='Nota do relatório de distribuição', null=True, verbose_name='Nota do Relatório de Distribuição')),
                ('report_cover_header_line_1', models.CharField(blank=True, help_text='Linha 1 do cabeçalho do relatório', max_length=100, null=True, verbose_name='Linha 1 do Cabeçalho do Relatório')),
                ('report_cover_header_line_2', models.CharField(blank=True, help_text='Linha 2 do cabeçalho do relatório', max_length=100, null=True, verbose_name='Linha 2 do Cabeçalho do Relatório')),
                ('report_cover_header_line_3', models.CharField(blank=True, help_text='Linha 3 do cabeçalho do relatório', max_length=100, null=True, verbose_name='Linha 3 do Cabeçalho do Relatório')),
                ('report_cover_footer_line_1', models.CharField(blank=True, help_text='Linha 1 do rodapé do relatório', max_length=100, null=True, verbose_name='Linha 1 do Rodapé do Relatório')),
                ('report_cover_footer_line_2', models.CharField(blank=True, help_text='Linha 2 do rodapé do relatório', max_length=100, null=True, verbose_name='Linha 2 do Rodapé do Relatório')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('extraction_unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report_settings', to='core.extractionunit', verbose_name='Unidade de Extração')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Configuração de Relatórios da Unidade',
                'verbose_name_plural': 'Configurações de Relatórios das Unidades',
                'db_table': 'extr_unit_report_settings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='extr_unit_r_created_04db03_idx')],
            },
        ),
    ]
