# Generated by Django 4.2.26 on 2025-12-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_extractionunitreportsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionunitstoragemedia',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Indica se este é o meio de armazenamento padrão para a unidade', verbose_name='Padrão'),
        ),
        migrations.AddField(
            model_name='extractionunitstoragemedia',
            name='total_storage_space',
            field=models.BigIntegerField(blank=True, help_text='Espaço total de armazenamento do meio de armazenamento', null=True, verbose_name='Espaço Total de Armazenamento'),
        ),
        migrations.AddField(
            model_name='extractionunitstoragemedia',
            name='used_storage_space',
            field=models.BigIntegerField(blank=True, help_text='Espaço utilizado de armazenamento do meio de armazenamento', null=True, verbose_name='Espaço Utilizado de Armazenamento'),
        ),
    ]
