# Generated by Django 5.2.8 on 2025-11-29 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_tables', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Excluído em')),
                ('version', models.IntegerField(default=1, verbose_name='Versão do Registro')),
                ('requested_at', models.DateTimeField(blank=True, help_text='Data e hora da solicitação', null=True, verbose_name='Solicitada em')),
                ('requested_device_amount', models.PositiveSmallIntegerField(blank=True, default=1, help_text='Quantidade de dispositivos solicitados', null=True, verbose_name='Quantidade de Dispositivos')),
                ('requester_reply_email', models.EmailField(blank=True, help_text='E-mail de resposta', max_length=254, null=True, verbose_name='E-mail de Resposta')),
                ('requester_authority_name', models.CharField(blank=True, help_text='Nome completo da autoridade solicitante', max_length=300, null=True, verbose_name='Nome da Autoridade')),
                ('request_procedures', models.CharField(blank=True, help_text='Procedimentos (ex: IP, PJ, etc)', max_length=512, null=True, verbose_name='Procedimentos')),
                ('additional_info', models.TextField(blank=True, help_text='Informações adicionais', null=True, verbose_name='Informações Adicionais')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('assigned', 'Aguardando Material'), ('received', 'Material Recebido'), ('waiting_start', 'Aguardando Início'), ('in_progress', 'Em Andamento'), ('waiting_collection', 'Aguardando Coleta')], default='assigned', help_text='Status da solicitação de extração.', max_length=50, verbose_name='Status')),
                ('received_at', models.DateTimeField(blank=True, help_text='Data e hora do recebimento do material', null=True, verbose_name='Recebido em')),
                ('receipt_notes', models.TextField(blank=True, help_text='Observações sobre o recebimento do material', null=True, verbose_name='Observações')),
                ('is_legacy', models.BooleanField(blank=True, help_text='Indica se a solicitação de extração é legada', null=True, verbose_name='É legado')),
                ('spreadsheet_line', models.IntegerField(blank=True, help_text='Linha do arquivo de planilha', null=True, verbose_name='Linha do arquivo de planilha')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('crime_category', models.ForeignKey(blank=True, help_text='Categoria de Crime', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_crime_types', to='base_tables.crimecategory', verbose_name='Categoria de Crime')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('extraction_unit', models.ForeignKey(blank=True, help_text='Unidade de extração', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_requested_extraction_units', to='core.extractionunit', verbose_name='Unidade de Extração')),
                ('received_by', models.ForeignKey(blank=True, help_text='Usuário que recebeu o material', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recebido por')),
                ('requester_agency_unit', models.ForeignKey(blank=True, help_text='Unidade solicitante', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_requester_agency_units', to='base_tables.agencyunit', verbose_name='Unidade Solicitante')),
                ('requester_authority_position', models.ForeignKey(blank=True, help_text='Cargo da autoridade solicitante', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_requester_authority_positions', to='base_tables.employeeposition', verbose_name='Cargo da Autoridade')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Solicitação de Extração',
                'verbose_name_plural': 'Solicitações de Extração',
                'db_table': 'extraction_request',
            },
        ),
    ]
